# Setup grafana
# Variables: grafana_version
---
- name: Install requirements
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - libfontconfig1
    - musl

- name: Download grafana package
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}+security~01_amd64.deb
    dest: /tmp/grafana_{{ grafana_version }}+security-01_amd64.deb
    mode: '0644'

- name: Install grafana
  ansible.builtin.apt:
    deb: /tmp/grafana_{{ grafana_version }}+security-01_amd64.deb

- name: Start and enable grafana-server service
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: restarted
    daemon_reload: true

- name: Ensure grafana-server is running
  ansible.builtin.wait_for:
    port: 3000
    delay: 10
    timeout: 300
    state: started

- name: Remove grafana package
  ansible.builtin.file:
    state: absent
    path: /tmp/grafana_{{ grafana_version }}+security-01_amd64.deb
